### PR TITLE
Fix tests

### LINKED ISSUE #141: Estado.name es None
Me parece que con los cambios que se realizaron de mypy https://github.com/cuenca-mx/speid/blob/97637ffaa9aac0fceb2ce18580084272f1c0fb3f/speid/commands/spei.py#L28
Al ejecutarse esta línea de código como comando, Estado.failed.name es None y hace que el comando no pueda ejecutarse

### LINKED ISSUE #156: Tests ya no pasan haciendo make test
En local, se podía hacer solo `make test` y los tests pasaban

### PR DESCRIPTION
**Pull request by ricardo8990**
closes #156 
closes #141

Tiene algunos breaking changes:
- Ya no soporta usar el API callback, ahora toda comunicación es por la queue
- Se elimina la tabla Requests, ahora usa el `logging` para las peticiones y respuestas.

### CODE REVIEW

**Comment by matin** [comment]
Still not at 95+ coverage

**Comment by matin** [comment]
Exclude `commands` from coverage. You can do it in `setup.cfg`, or you should be able to put `# pragmatic: no cover` at the top of the files

**Comment by ricardo8990** [comment]
@matin do we actually need `docker` commands? And this: https://github.com/cuenca-mx/speid/blob/93bb9ffbe0cc5a0d6785b5749a0ad6543e1e9bf1/speid/commands/__init__.py#L10-L19

**Comment by matin** [comment]
> @matin do we actually need `docker` commands? And this: https://github.com/cuenca-mx/speid/blob/93bb9ffbe0cc5a0d6785b5749a0ad6543e1e9bf1/speid/commands/__init__.py#L10-L19

No

**Pull request merged**
